"""Constants for Tandem REST API — column families, element flags, qualified columns."""

# Element key sizes (bytes)
ELEMENT_FLAGS_SIZE = 4
ELEMENT_ID_SIZE = 20
ELEMENT_ID_WITH_FLAGS_SIZE = ELEMENT_FLAGS_SIZE + ELEMENT_ID_SIZE
MODEL_ID_SIZE = 16
SYSTEM_ID_SIZE = 9

# Element flags — identify what type of element this is
ELEMENT_FLAGS_SIMPLE_ELEMENT = 0x00000000
ELEMENT_FLAGS_ROOM = 0x00000005
ELEMENT_FLAGS_FAMILY_TYPE = 0x01000000
ELEMENT_FLAGS_LEVEL = 0x01000001
ELEMENT_FLAGS_STREAM = 0x01000003
ELEMENT_FLAGS_SYSTEM = 0x01000004
ELEMENT_FLAGS_GENERIC_ASSET = 0x01000005
ELEMENT_FLAGS_COLLECTION = 0x01000006
ELEMENT_FLAGS_TICKET = 0x01000007
ELEMENT_FLAGS_DELETED = 0xFFFFFFFE

# Key flags
KEY_FLAGS_PHYSICAL = 0x00000000
KEY_FLAGS_LOGICAL = 0x01000000

# Column families — data grouping
COLUMN_FAMILIES_DTPROPERTIES = "z"
COLUMN_FAMILIES_LMV = "0"
COLUMN_FAMILIES_SOURCE = "r"
COLUMN_FAMILIES_STANDARD = "n"
COLUMN_FAMILIES_STATUS = "s"
COLUMN_FAMILIES_SYSTEMS = "m"
COLUMN_FAMILIES_REFS = "l"
COLUMN_FAMILIES_XREFS = "x"

# Column names
COLUMN_NAMES_BOUNDING_BOX = "0"
COLUMN_NAMES_CATEGORY_ID = "c"
COLUMN_NAMES_CLASSIFICATION = "v"
COLUMN_NAMES_OCLASSIFICATION = "!v"
COLUMN_NAMES_ELEMENT_FLAGS = "a"
COLUMN_NAMES_ELEVATION = "el"
COLUMN_NAMES_FAMILY_TYPE = "t"
COLUMN_NAMES_IS_ASSET = "ia"
COLUMN_NAMES_LEVEL = "l"
COLUMN_NAMES_NAME = "n"
COLUMN_NAMES_ONAME = "!n"
COLUMN_NAMES_PARENT = "p"
COLUMN_NAMES_PRIORITY = "pr"
COLUMN_NAMES_OPEN_DATE = "od"
COLUMN_NAMES_CLOSE_DATE = "cd"
COLUMN_NAMES_ROOMS = "r"
COLUMN_NAMES_STATE = "s"
COLUMN_NAMES_SETTINGS = "s"
COLUMN_NAMES_SYSTEM_CLASS = "b"
COLUMN_NAMES_TANDEM_CATEGORY = "z"
COLUMN_NAMES_UNIFORMAT_CLASS = "u"

# Qualified columns — family:column shorthand
QC_KEY = "k"
QC_CLASSIFICATION = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_CLASSIFICATION}"
QC_OCLASSIFICATION = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_OCLASSIFICATION}"
QC_ELEMENT_FLAGS = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_ELEMENT_FLAGS}"
QC_ELEVATION = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_ELEVATION}"
QC_FAMILY_TYPE = f"{COLUMN_FAMILIES_REFS}:{COLUMN_NAMES_FAMILY_TYPE}"
QC_IS_ASSET = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_IS_ASSET}"
QC_LEVEL = f"{COLUMN_FAMILIES_REFS}:{COLUMN_NAMES_LEVEL}"
QC_NAME = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_NAME}"
QC_ONAME = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_ONAME}"
QC_PARENT = f"{COLUMN_FAMILIES_REFS}:{COLUMN_NAMES_PARENT}"
QC_ROOMS = f"{COLUMN_FAMILIES_REFS}:{COLUMN_NAMES_ROOMS}"
QC_XROOMS = f"{COLUMN_FAMILIES_XREFS}:{COLUMN_NAMES_ROOMS}"
QC_XPARENT = f"{COLUMN_FAMILIES_XREFS}:{COLUMN_NAMES_PARENT}"
QC_STATE = f"{COLUMN_FAMILIES_STATUS}:{COLUMN_NAMES_STATE}"
QC_SETTINGS = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_SETTINGS}"
QC_SYSTEM_CLASS = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_SYSTEM_CLASS}"
QC_OSYSTEM_CLASS = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_SYSTEM_CLASS}"
QC_PRIORITY = f"{COLUMN_FAMILIES_STANDARD}:{COLUMN_NAMES_PRIORITY}"

# Mutation actions
MUTATE_ACTIONS_DELETE = "d"
MUTATE_ACTIONS_DELETE_ROW = "a"
MUTATE_ACTIONS_INSERT = "i"
MUTATE_ACTIONS_INSERT_IF_DIFFERENT = "c"

# System class names (bitmask positions)
SYSTEM_CLASS_NAMES = [
    "Supply Air",
    "Return Air",
    "Exhaust Air",
    "Hydronic Supply",
    "Hydronic Return",
    "Domestic Hot Water",
    "Domestic Cold Water",
    "Sanitary",
    "Power",
    "Vent",
    "Controls",
    "Fire Protection Wet",
    "Fire Protection Dry",
    "Fire Protection Pre-Action",
    "Other Air",
    "Other",
    "Fire Protection Other",
    "Communication",
    "Data Circuit",
    "Telephone",
    "Security",
    "Fire Alarm",
    "Nurse Call",
    "Switch Topology",
    "Cable Tray Conduit",
    "Storm",
]


def system_class_to_list(flags: int) -> list[str]:
    """Decode system class bitmask to list of class names."""
    if flags is None or flags == 0:
        return []
    return [SYSTEM_CLASS_NAMES[i] for i in range(len(SYSTEM_CLASS_NAMES)) if flags & (1 << i)]


def get_default_model_id(facility_id: str) -> str:
    """Convert facility URN to default model URN."""
    return facility_id.replace("urn:adsk.dtt:", "urn:adsk.dtm:")
